apiVersion: apps/v1
kind: Deployment
metadata:
  name: 01-order-backend
  namespace: youngil-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 01-order-backend
  template:
    metadata:
      labels:
        app: 01-order-backend
    spec:
      containers:
      - name: 01-order-backend
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/01-order-backend:latest
        ports:
        - containerPort: 8080 # 스프링에서 쓰는 포트번호
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: 01-app-secrets  # 노션에 만드는 명령어 있음.
              key: DB_HOST #명령어 통해서 사용할 것들임임
        - name: DB_PW #application.yml에서 찾는 지표
          valueFrom:
            secretKeyRef:
              name: 01-app-secrets
              key: DB_PW
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: 01-app-secrets
              key: REDIS_HOST
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: 01-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: 01-app-secrets
              key: AWS_SECRET
        # 컨테이너 상태 확인 
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /product/list

---
apiVersion: v1
kind: Service
metadata:
  name: 01-order-backend-service
  namespace: youngil-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: 01-order-backend
---